### ISSUE TITLE
Tidying up the Stock identification Services

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-prod/icesSLD#3]
To have alignment across SD and SAG

1. Stock DB will take the ID from vocab.ices.dk as the StockKey 
2. In StockDB, existing internal ID will be renamed to StockDatabaseID
3. StockKey (from vocab) will be exposed as the main stock identifier
4. OldStockCode will become PreviousStockKeyLabel
5. New field: PreviousStockKey
6. New Service: return most recent StockKey based on input: StockKey

For reference:
Link to CodeType:
http://vocab.ices.dk/?ref=357
Link to Code:
http://vocab.ices.dk/?codeID=136481

**Comment by mikeydrew** [comment]
All actions have been completed. New service, return most recent StockKey, added here : -
http://sd.ices.dk/services/

Named http://sd.ices.dk/services/stockkey/136481?type=xml 

The following changes were also made : -

1. Service http://sd.ices.dk/services/code/her/2015 was renamed http://sd.ices.dk/services/stockkeylabel/her/2015 

2. AssessmentKey from SG was added to related services

3. To follow the naming convention, “description” was renamed “StockKeyDescription”  in related services
